import { Inter } from 'next/font/google';
import "./globals.css";
import { Box } from "@mui/material";
import Header from "./components/header";
import Footer from "./components/footer";
import Sidebar from "./components/sidebar";

export const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <body className={`${inter.className} antialiased`}>
        <Box>
          <Header/>
          <Sidebar/>
          <Footer/>
        </Box>
        {children}
      </body>
    </html>
  );
}
